// LOCALHOST
###
GET http://localhost:3000/products


// LOCALHOST
### Get all contacts
GET http://localhost:3000/products/652b9e201aa9da6dae725fc4




### Create product
POST http://localhost:3000/products HTTP/1.1
content-type: application/json

{
  "name": "New Product 10",
  "description": "A description for the new product",
  "price": 19.99
}


### PUT contact
PUT http://localhost:3000/products/652b9e201aa9da6dae725fc4  HTTP/1.1
content-type: application/json

{
  "name": "Update Producyhghtjk hjj 2",
  "description": "A descriptio rkgj gn for the new product",
  "price": 19.993
}
### DELETE contact
DELETE http://localhost:3000/products/6541afc599d30f8c4a801b13 HTTP/1.1




// PRODUCTION Deploy
### Get all contacts
GET https://sales-inventory.onrender.com/products




### Create product
POST https://sales-inventory.onrender.com/products HTTP/1.1
content-type: application/json

{
  "name": "New Product 10",
  "description": "A description for the new product",
  "price": 19.99
}


### PUT contact
PUT https://sales-inventory.onrender.com/products/652b9f0de1e784527a52eb87 HTTP/1.1
content-type: application/json

{
  "name": "Update Product 2",
  "description": "A description for the new product",
  "price": 19.99
}
### DELETE contact
DELETE https://sales-inventory.onrender.com/products/652b9f0de1e784527a52eb87 HTTP/1.1